swagger: '2.0'
info:
  license:
    name: Yodlee Developer License
    url: https://developer.yodlee.com/terms/condition#_Services_1
  contact:
    email: developer@yodlee.com
  description: 'This file describes the Yodlee Platform APIs using the swagger notation. You can use this swagger file to generate client side SDKs to the Yodlee Platform APIs for many different programming languages. Yodlee API v1.1 - Overview</a>.<br><br>You will have to set the header before making the API call. The following headers apply to all the APIs:<ul><li>Authorization: This header holds the access token</li> <li> Api-Version: 1.1</li></ul><b>Note</b>: If there are any API-specific headers, they are mentioned explicitly in the respective API''s description.'
  termsOfService: https://developer.yodlee.com/terms/condition
  title: Yodlee Core APIs Account Token Statements API
  version: 1.1.0
basePath: /
tags:
- name: Statements
  description: Statements API
paths:
  /statements:
    get:
      summary: Get Statements
      deprecated: false
      produces:
      - application/json;charset=UTF-8
      description: The statements service is used to get the list of statement related information. <br>By default, all the latest statements of active and to be closed accounts are retrieved for the user. <br>Certain sites do not have both a statement date and a due date. When a fromDate is passed as an input, all the statements that have the due date on or after the passed date are retrieved. <br>For sites that do not have the due date, statements that have the statement date on or after the passed date are retrieved. <br>The default value of "isLatest" is true. To retrieve historical statements isLatest needs to be set to false.<br>
      operationId: getStatements
      responses:
        200:
          schema:
            $ref: '#/definitions/StatementResponse'
          description: OK
        400:
          schema:
            $ref: '#/definitions/YodleeError'
          description: 'Y800 : Invalid value for accountId<br>Y800 : Invalid value for status<br>Y805 : Multiple containers not supported<br>Y800 : Invalid value for container<br>Y800 : Invalid value for isLatest<br>Y800 : Invalid value for fromDate<br>'
        401:
          description: Unauthorized
        404:
          description: Not Found
      parameters:
      - in: query
        allowEmptyValue: false
        name: accountId
        description: accountId
        type: string
        required: false
      - in: query
        allowEmptyValue: false
        name: container
        description: creditCard/loan/insurance
        type: string
        required: false
      - in: query
        allowEmptyValue: false
        name: fromDate
        description: from date for statement retrieval (YYYY-MM-DD)
        type: string
        required: false
      - in: query
        allowEmptyValue: false
        name: isLatest
        description: isLatest (true/false)
        type: string
        required: false
      - in: query
        allowEmptyValue: false
        name: status
        description: ACTIVE,TO_BE_CLOSED,CLOSED
        type: string
        required: false
      tags:
      - Statements
definitions:
  Money:
    type: object
    title: Money
    properties:
      amount:
        format: double
        description: Value of amount.
        type: number
      convertedAmount:
        format: double
        description: Value of the converted amount.
        type: number
      currency:
        description: Currency should be a valid three-letter ISO Code.
        type: string
        enum:
        - USD
        - AUD
        - BRL
        - CAD
        - EUR
        - GBP
        - HKD
        - IDR
        - INR
        - JPY
        - NZD
        - SGD
        - ZAR
        - CNY
        - VND
        - MYR
        - CHF
        - AED
        - AFA
        - ALL
        - AMD
        - ANG
        - AOA
        - ARS
        - AWG
        - AZM
        - BAM
        - BBD
        - BDT
        - BGL
        - BHD
        - BIF
        - BMD
        - BND
        - BOB
        - BSD
        - BTN
        - BWP
        - BYR
        - BZD
        - CDF
        - CLP
        - COP
        - CRC
        - CUP
        - CVE
        - CYP
        - CZK
        - DJF
        - DKK
        - DOP
        - DZD
        - EEK
        - EGP
        - ERN
        - ETB
        - FJD
        - FKP
        - GEL
        - GGP
        - GHC
        - GIP
        - GMD
        - GNF
        - GTQ
        - GYD
        - HNL
        - HRK
        - HTG
        - HUF
        - ILS
        - IMP
        - IQD
        - IRR
        - ISK
        - JEP
        - JMD
        - JOD
        - KES
        - KGS
        - KHR
        - KMF
        - KPW
        - KRW
        - KWD
        - KYD
        - KZT
        - LAK
        - LBP
        - LKR
        - LRD
        - LSL
        - LTL
        - LVL
        - LYD
        - MAD
        - MDL
        - MGF
        - MKD
        - MMK
        - MNT
        - MOP
        - MRO
        - MTL
        - MUR
        - MVR
        - MWK
        - MXN
        - MZM
        - NAD
        - NGN
        - NIO
        - NOK
        - NPR
        - OMR
        - PAB
        - PEN
        - PGK
        - PHP
        - PKR
        - PLN
        - PYG
        - QAR
        - ROL
        - RUR
        - RWF
        - SAR
        - SBD
        - SCR
        - SDD
        - SEK
        - SHP
        - SIT
        - SKK
        - SLL
        - SOS
        - SPL
        - SRG
        - STD
        - SVC
        - SYP
        - SZL
        - THB
        - TJR
        - TMM
        - TND
        - TOP
        - TRL
        - TTD
        - TVD
        - TWD
        - TZS
        - UAH
        - UGX
        - UYU
        - UZS
        - VEB
        - VUV
        - WST
        - XAF
        - XAG
        - XAU
        - XCD
        - XDR
        - XOF
        - XPD
        - XPF
        - XPT
        - YER
        - YUM
        - ZMK
        - ZWD
        - ADP
        - ATS
        - BEF
        - BUK
        - CSD
        - CSK
        - DDM
        - DEM
        - ECS
        - ESP
        - FIM
        - GRD
        - GWP
        - IEP
        - ITL
        - LUF
        - MLF
        - NLG
        - PTE
        - SUR
        - TPE
        - UAK
        - XBA
        - XBB
        - XBC
        - XBD
        - XEU
        - XFO
        - XFU
        - XGF
        - XMK
        - XRM
        - XTS
        - YDD
        - YUD
        - ZRN
        - TJS
        - RON
        - BGN
        - BTC
        - XBT
        - CNH
        - RUB
        - TRY
        - GHS
        - TMT
        - ZMW
        - VEF
        - SSP
        - ALK
      convertedCurrency:
        description: Currency should be a valid three-letter ISO Code.
        type: string
        enum:
        - USD
        - AUD
        - BRL
        - CAD
        - EUR
        - GBP
        - HKD
        - IDR
        - INR
        - JPY
        - NZD
        - SGD
        - ZAR
        - CNY
        - VND
        - MYR
        - CHF
        - AED
        - AFA
        - ALL
        - AMD
        - ANG
        - AOA
        - ARS
        - AWG
        - AZM
        - BAM
        - BBD
        - BDT
        - BGL
        - BHD
        - BIF
        - BMD
        - BND
        - BOB
        - BSD
        - BTN
        - BWP
        - BYR
        - BZD
        - CDF
        - CLP
        - COP
        - CRC
        - CUP
        - CVE
        - CYP
        - CZK
        - DJF
        - DKK
        - DOP
        - DZD
        - EEK
        - EGP
        - ERN
        - ETB
        - FJD
        - FKP
        - GEL
        - GGP
        - GHC
        - GIP
        - GMD
        - GNF
        - GTQ
        - GYD
        - HNL
        - HRK
        - HTG
        - HUF
        - ILS
        - IMP
        - IQD
        - IRR
        - ISK
        - JEP
        - JMD
        - JOD
        - KES
        - KGS
        - KHR
        - KMF
        - KPW
        - KRW
        - KWD
        - KYD
        - KZT
        - LAK
        - LBP
        - LKR
        - LRD
        - LSL
        - LTL
        - LVL
        - LYD
        - MAD
        - MDL
        - MGF
        - MKD
        - MMK
        - MNT
        - MOP
        - MRO
        - MTL
        - MUR
        - MVR
        - MWK
        - MXN
        - MZM
        - NAD
        - NGN
        - NIO
        - NOK
        - NPR
        - OMR
        - PAB
        - PEN
        - PGK
        - PHP
        - PKR
        - PLN
        - PYG
        - QAR
        - ROL
        - RUR
        - RWF
        - SAR
        - SBD
        - SCR
        - SDD
        - SEK
        - SHP
        - SIT
        - SKK
        - SLL
        - SOS
        - SPL
        - SRG
        - STD
        - SVC
        - SYP
        - SZL
        - THB
        - TJR
        - TMM
        - TND
        - TOP
        - TRL
        - TTD
        - TVD
        - TWD
        - TZS
        - UAH
        - UGX
        - UYU
        - UZS
        - VEB
        - VUV
        - WST
        - XAF
        - XAG
        - XAU
        - XCD
        - XDR
        - XOF
        - XPD
        - XPF
        - XPT
        - YER
        - YUM
        - ZMK
        - ZWD
        - ADP
        - ATS
        - BEF
        - BUK
        - CSD
        - CSK
        - DDM
        - DEM
        - ECS
        - ESP
        - FIM
        - GRD
        - GWP
        - IEP
        - ITL
        - LUF
        - MLF
        - NLG
        - PTE
        - SUR
        - TPE
        - UAK
        - XBA
        - XBB
        - XBC
        - XBD
        - XEU
        - XFO
        - XFU
        - XGF
        - XMK
        - XRM
        - XTS
        - YDD
        - YUD
        - ZRN
        - TJS
        - RON
        - BGN
        - BTC
        - XBT
        - CNH
        - RUB
        - TRY
        - GHS
        - TMT
        - ZMW
        - VEF
        - SSP
        - ALK
  Statement:
    type: object
    title: Statement
    properties:
      apr:
        format: double
        description: 'The APR applied to the balance on the credit card account, as available in the statement.<br><b>Note:</b> In case of variable APR, the APR available on the statement might differ from the APR available at the account-level.<br><br><b>Applicable containers</b>: creditCard, loan, insurance<br>'
        readOnly: true
        type: number
      cashApr:
        format: double
        description: 'The APR applicable to cash withdrawals on the credit card account.<br><br><b>Applicable containers</b>: creditCard, loan, insurance<br>'
        readOnly: true
        type: number
      billingPeriodStart:
        description: 'The start date of the statement period.<br><br><b>Applicable containers</b>: creditCard, loan, insurance<br>'
        readOnly: true
        type: string
      dueDate:
        description: 'The date by when the minimum payment is due to be paid.<br><b>Note:</b> The due date that appears in the statement may differ from the due date at the account-level.<br><br><b>Applicable containers</b>: creditCard, loan, insurance<br>'
        readOnly: true
        type: string
      interestAmount:
        description: 'The interest amount that is part of the amount due or the payment amount.<br><br><b>Applicable containers</b>: creditCard, loan, insurance<br>'
        readOnly: true
        $ref: '#/definitions/Money'
      statementDate:
        description: 'The date on which the statement is generated.<br><br><b>Applicable containers</b>: creditCard, loan, insurance<br>'
        readOnly: true
        type: string
      cashAdvance:
        description: 'Cash Advance is the amount that is withdrawn from credit card over the counter or from an ATM up to the available credit/cash limit.<br><br><b>Applicable containers</b>: creditCard, loan, insurance<br>'
        readOnly: true
        $ref: '#/definitions/Money'
      billingPeriodEnd:
        description: 'The end date of the statement period.<br><br><b>Applicable containers</b>: creditCard, loan, insurance<br>'
        readOnly: true
        type: string
      principalAmount:
        description: 'The principal amount that is part of the amount due or the payment amount.<br><br><b>Applicable containers</b>: creditCard, loan, insurance<br>'
        readOnly: true
        $ref: '#/definitions/Money'
      loanBalance:
        description: 'The outstanding principal balance on the loan account.<br><br><b>Applicable containers</b>: creditCard, loan, insurance<br>'
        readOnly: true
        $ref: '#/definitions/Money'
      amountDue:
        description: 'The total amount owed at the end of the billing period.<br><br><b>Applicable containers</b>: creditCard, loan, insurance<br>'
        readOnly: true
        $ref: '#/definitions/Money'
      accountId:
        format: int64
        description: 'Account to which the statement belongs to.<br><br><b>Applicable containers</b>: creditCard, loan, insurance<br>'
        readOnly: true
        type: integer
      lastUpdated:
        description: 'The date when the account was last updated by Yodlee.<br><br><b>Applicable containers</b>: creditCard, loan, insurance<br>'
        readOnly: true
        type: string
      isLatest:
        description: 'The field is set to true if the statement is the latest generated statement.<br><br><b>Applicable containers</b>: creditCard, loan, insurance<br>'
        readOnly: true
        type: boolean
      minimumPayment:
        description: '<b>Credit Card:</b> The minimum amount that the consumer has to pay every month on the credit card account. Data provides an up-to-date information to the consumer.<br><br><b>Applicable containers</b>: creditCard, loan, insurance<br>'
        readOnly: true
        $ref: '#/definitions/Money'
      lastPaymentDate:
        description: 'The date on which the last payment was done during the billing cycle.<br><br><b>Applicable containers</b>: creditCard, loan, insurance<br>'
        readOnly: true
        type: string
      lastPaymentAmount:
        description: 'The last payment done for the previous billing cycle in the current statement period.<br><br><b>Applicable containers</b>: creditCard, loan, insurance<br>'
        readOnly: true
        $ref: '#/definitions/Money'
      id:
        format: int64
        description: 'Unique identifier for the statement.<br><br><b>Applicable containers</b>: creditCard, loan, insurance<br>'
        readOnly: true
        type: integer
      newCharges:
        description: 'New charges on the statement (i.e., charges since last statement to end of the billing period). Applicable to line of credit loan type.<br><br><b>Applicable containers</b>: creditCard, loan, insurance<br>'
        readOnly: true
        $ref: '#/definitions/Money'
  StatementResponse:
    type: object
    title: StatementResponse
    properties:
      statement:
        readOnly: true
        type: array
        items:
          $ref: '#/definitions/Statement'
  YodleeError:
    type: object
    title: YodleeError
    properties:
      errorMessage:
        description: The descriptive message that explains the error scenario.
        readOnly: true
        type: string
      errorCode:
        description: The error code follows the format YNNN. The error codes do not change. New error codes may be added as we introduce new features and enhance functionalities.
        readOnly: true
        type: string
      referenceCode:
        description: Unique Yodlee identifier used to troubleshoot issues at Yodlee's end.
        readOnly: true
        type: string
